
FT_DPCM_PTR=$c000
	.export _ftm_test_music_data
;this file for FamiTone2 library generated by text2data tool

;this file for FamiTone2 library generated by text2data tool

_ftm_test_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,348,290 ; New song

@instruments:
	.byte $30 ;instrument $00
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env1,@env5,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env2,@env6,@env0
	.byte $00
	.byte $30 ;instrument $04
	.word @env2,@env7,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env2,@env8,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env2,@env9,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $08
	.word @env3,@env10,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $ca,$c8,$c6,$c4,$c2,$c0,$00,$05
@env2:
	.byte $cd,$cc,$cb,$ca,$c9,$c9,$c8,$c7,$c6,$c5,$c3,$c1,$00,$0b
@env3:
	.byte $c1,$05,$c0,$00,$02
@env4:
	.byte $cf,$00,$00
@env5:
	.byte $c8,$cc,$c8,$c8,$ca,$00,$04
@env6:
	.byte $c0,$bd,$c4,$00,$00
@env7:
	.byte $c0,$bd,$c5,$00,$00
@env8:
	.byte $c0,$bb,$c2,$00,$00
@env9:
	.byte $c0,$bd,$c2,$00,$00
@env10:
	.byte $c0,$bf,$be,$bd,$bc,$bb,$b9,$00,$06


; New song
@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $fb,$04,$8c,$40,$8d,$40,$8d,$4e,$85,$4a,$8d,$46,$8d,$46,$95,$4a
	.byte $85,$4e,$95
@ref1:
	.byte $44,$8d,$44,$8d,$44,$8d,$46,$85,$44,$9d,$3c,$a5
@ref2:
	.byte $40,$8d,$40,$8d,$4e,$85,$4a,$8d,$46,$8d,$46,$95,$4a,$85,$4e,$95
	.byte $ff,$0c
	.word @ref1
@ref4:
	.byte $f9,$85
@ref5:
	.byte $00,$f9,$83
@ref6:
	.byte $f9,$85
@ref7:
	.byte $00,$f9,$83
	.byte $fd
	.word @song0ch0loop

; New song
@song0ch1:
@song0ch1loop:
@ref8:
	.byte $80,$36,$b5,$3c,$a5,$40,$9d
@ref9:
	.byte $36,$b5,$3c,$9d,$32,$a5
@ref10:
	.byte $36,$b5,$3c,$a5,$40,$9d
	.byte $ff,$06
	.word @ref9
@ref12:
	.byte $84,$58,$8d,$58,$85,$58,$8d,$58,$8d,$86,$58,$8d,$58,$8d,$58,$8d
	.byte $58,$85,$58,$8d
@ref13:
	.byte $8a,$58,$8d,$58,$8d,$58,$8d,$58,$85,$58,$8d,$88,$58,$8d,$58,$8d
	.byte $58,$85,$58,$8d
	.byte $ff,$12
	.word @ref12
	.byte $ff,$12
	.word @ref13
	.byte $fd
	.word @song0ch1loop

; New song
@song0ch2:
@song0ch2loop:
@ref16:
	.byte $8f,$80,$28,$85,$11,$29,$8e,$32,$85,$80,$10,$85,$28,$85,$11,$29
	.byte $8e,$32,$85,$33,$80,$17,$2e,$85,$17,$2f,$8e,$32,$85,$80,$16,$85
	.byte $2e,$85,$17,$2e,$81
@ref17:
	.byte $8e,$32,$85,$33,$80,$15,$2c,$85,$15,$2d,$8e,$32,$85,$80,$14,$85
	.byte $2c,$85,$15,$2d,$8e,$32,$85,$33,$80,$0d,$24,$85,$0d,$25,$8e,$32
	.byte $85,$80,$0c,$85,$24,$85,$0d,$24,$81
@ref18:
	.byte $8e,$32,$85,$33,$80,$11,$28,$85,$11,$29,$8e,$32,$85,$80,$10,$85
	.byte $28,$85,$11,$29,$8e,$32,$85,$33,$80,$17,$2e,$85,$17,$2f,$8e,$32
	.byte $85,$80,$16,$85,$2e,$85,$17,$2e,$81
	.byte $ff,$21
	.word @ref17
@ref20:
	.byte $00,$f9,$83
@ref21:
	.byte $00,$f9,$83
@ref22:
	.byte $00,$f9,$83
@ref23:
	.byte $00,$f9,$83
	.byte $fd
	.word @song0ch2loop

; New song
@song0ch3:
@song0ch3loop:
@ref24:
	.byte $8f,$82,$08,$9d,$08,$9d,$08,$9d,$08,$8d
@ref25:
	.byte $8f,$08,$9d,$08,$9d,$08,$9d,$08,$8d
	.byte $ff,$09
	.word @ref25
	.byte $ff,$09
	.word @ref25
@ref28:
	.byte $08,$b5,$08,$8d,$08,$9d,$08,$85,$08,$8d
	.byte $ff,$0a
	.word @ref28
	.byte $ff,$0a
	.word @ref28
	.byte $ff,$0a
	.word @ref28
	.byte $fd
	.word @song0ch3loop

; New song
@song0ch4:
@song0ch4loop:
@ref32:
	.byte $f9,$85
@ref33:
	.byte $f9,$85
@ref34:
	.byte $f9,$85
@ref35:
	.byte $f9,$85
@ref36:
	.byte $f9,$85
@ref37:
	.byte $f9,$85
@ref38:
	.byte $f9,$85
@ref39:
	.byte $f9,$85
	.byte $fd
	.word @song0ch4loop
